version: '3.4'

services:
  edubot_hintserver_server:
    image: ${DOCKER_REGISTRY-}edubot_hintserver_server
    build:
      context: Edubot.HintServer.Server   
    ports:
      - 6190:8000
    volumes:
      - ./app.config.json:/app.config.json
